//! Generate Kotlin/JVM bindings and JNI entry points from validated Ketox metadata.
//!
//! In a Cargo build script, call [`generate_from_file`] with `OUT_DIR` as the
//! output directory, then include `ketox_jni.rs` at the library's crate root.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use ketox_core::{Module, Type, parse_source, validate_module};

/// All artifacts for one module. Their contents are stable for identical metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedBindings {
    pub kotlin: String,
    pub rust: String,
    pub metadata: String,
}

/// Generate artifacts without touching the filesystem.
pub fn generate(module: &Module) -> Result<GeneratedBindings, String> {
    validate_module(module)?;
    let kotlin = generate_kotlin(module);
    let rust = generate_rust(module);
    let metadata = serde_json::to_string_pretty(module)
        .map_err(|error| format!("could not serialize Ketox metadata: {error}"))?
        + "\n";
    Ok(GeneratedBindings {
        kotlin,
        rust,
        metadata,
    })
}

/// Parse a Rust source file and write `ketox_jni.rs`, `<Class>.kt`, and
/// `ketox-metadata.json` into `output`.
///
/// Source and metadata validation happen before any output files are written.
/// Build scripts should also emit `cargo:rerun-if-changed=<source>` themselves.
pub fn generate_from_file(
    source: impl AsRef<Path>,
    package: &str,
    class_name: &str,
    library_name: &str,
    output: impl AsRef<Path>,
) -> Result<GeneratedBindings, String> {
    let source = source.as_ref();
    let source_text = fs::read_to_string(source)
        .map_err(|error| format!("could not read Rust source '{}': {error}", source.display()))?;
    let module = parse_source(&source_text, package, class_name, library_name)
        .map_err(|error| format!("{}: {error}", source.display()))?;
    let generated = generate(&module)?;
    let output = output.as_ref();
    fs::create_dir_all(output).map_err(|error| {
        format!(
            "could not create output directory '{}': {error}",
            output.display()
        )
    })?;
    for (name, content) in [
        ("ketox_jni.rs".to_owned(), &generated.rust),
        (format!("{}.kt", module.class_name), &generated.kotlin),
        ("ketox-metadata.json".to_owned(), &generated.metadata),
    ] {
        let path = output.join(name);
        fs::write(&path, content)
            .map_err(|error| format!("could not write '{}': {error}", path.display()))?;
    }
    Ok(generated)
}

fn generate_kotlin(module: &Module) -> String {
    let mut output = format!(
        "// Generated by Ketox. Do not edit.\npackage {}\n\nobject {} {{\n",
        module.package, module.class_name
    );
    writeln!(output, "    init {{").unwrap();
    writeln!(output, "        try {{").unwrap();
    writeln!(
        output,
        "            java.lang.System.loadLibrary(\"{}\")",
        module.library_name
    )
    .unwrap();
    writeln!(
        output,
        "        }} catch (error: java.lang.UnsatisfiedLinkError) {{"
    )
    .unwrap();
    writeln!(output, "            throw java.lang.UnsatisfiedLinkError(").unwrap();
    writeln!(
        output,
        "                \"Ketox could not load native library '{}' on \" +",
        module.library_name
    )
    .unwrap();
    output.push_str(concat!(
        "                    java.lang.System.getProperty(\"os.name\") + \"/\" + java.lang.System.getProperty(\"os.arch\") +\n",
        "                    \". Build the Rust cdylib and add its directory to java.library.path. Current path: \" +\n",
        "                    java.lang.System.getProperty(\"java.library.path\")\n",
        "            ).also { it.initCause(error) }\n",
        "        }\n",
        "    }\n",
    ));
    for function in &module.functions {
        let parameters = function
            .parameters
            .iter()
            .map(|parameter| format!("{}: kotlin.{}", parameter.name, parameter.ty.kotlin_type()))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "\n    external fun {}({parameters}): kotlin.{}",
            function.kotlin_name,
            function.return_type.kotlin_type()
        )
        .unwrap();
    }
    output.push_str("}\n");
    output
}

fn generate_rust(module: &Module) -> String {
    let class_path = format!("{}/{}", module.package.replace('.', "/"), module.class_name);
    let class_symbol = jni_escape(&class_path);
    let mut output = String::from("// Generated by Ketox. Do not edit.\n");
    for function in &module.functions {
        let symbol = format!(
            "Java_{}_{}",
            class_symbol,
            jni_escape(&function.kotlin_name)
        );
        writeln!(output, "\n// JNI signature: {}", function.jni_signature()).unwrap();
        writeln!(
            output,
            "// SAFETY: this symbol uniquely identifies the validated Kotlin native method."
        )
        .unwrap();
        writeln!(output, "#[unsafe(no_mangle)]").unwrap();
        writeln!(output, "#[allow(non_snake_case)]").unwrap();
        writeln!(output, "pub extern \"system\" fn {symbol}<'local>(").unwrap();
        writeln!(output, "    mut __ketox_env: ::ketox::jni::JNIEnv<'local>,").unwrap();
        writeln!(output, "    _this: ::ketox::jni::objects::JObject<'local>,").unwrap();
        for (index, parameter) in function.parameters.iter().enumerate() {
            writeln!(
                output,
                "    __ketox_arg_{index}: {},",
                jni_rust_type(&parameter.ty, true)
            )
            .unwrap();
        }
        if function.return_type == Type::Unit {
            writeln!(output, ") {{").unwrap();
        } else {
            writeln!(
                output,
                ") -> {} {{",
                jni_rust_type(&function.return_type, false)
            )
            .unwrap();
        }
        writeln!(
            output,
            "    ::ketox::runtime::boundary(&mut __ketox_env, {}, |__ketox_env| {{",
            jni_default(&function.return_type)
        )
        .unwrap();
        let mut arguments = Vec::with_capacity(function.parameters.len());
        for (index, parameter) in function.parameters.iter().enumerate() {
            let argument = format!("__ketox_arg_{index}");
            arguments.push(match parameter.ty {
                Type::String | Type::Str => {
                    writeln!(
                        output,
                        "        let __ketox_value_{index} = ::ketox::runtime::read_string(__ketox_env, &{argument})?;"
                    )
                    .unwrap();
                    if parameter.ty == Type::Str {
                        format!("__ketox_value_{index}.as_str()")
                    } else {
                        format!("__ketox_value_{index}")
                    }
                }
                Type::Bool => format!("{argument} != 0"),
                _ => argument,
            });
        }
        let result_binding = if function.return_type == Type::Unit {
            ""
        } else {
            "let __ketox_result = "
        };
        writeln!(
            output,
            "        {result_binding}crate::{}({});",
            function.rust_name,
            arguments.join(", ")
        )
        .unwrap();
        match function.return_type {
            Type::String | Type::Str => output
                .push_str("        ::ketox::runtime::write_string(__ketox_env, __ketox_result)\n"),
            Type::Bool => output.push_str("        Ok(if __ketox_result { 1 } else { 0 })\n"),
            Type::Unit => output.push_str("        Ok(())\n"),
            _ => output.push_str("        Ok(__ketox_result)\n"),
        }
        output.push_str("    })\n}\n");
    }
    output
}

fn jni_rust_type(ty: &Type, input: bool) -> &'static str {
    match ty {
        Type::Bool => "::ketox::jni::sys::jboolean",
        Type::I8 => "::ketox::jni::sys::jbyte",
        Type::I16 => "::ketox::jni::sys::jshort",
        Type::I32 => "::ketox::jni::sys::jint",
        Type::I64 => "::ketox::jni::sys::jlong",
        Type::F32 => "::ketox::jni::sys::jfloat",
        Type::F64 => "::ketox::jni::sys::jdouble",
        Type::String | Type::Str if input => "::ketox::jni::objects::JString<'local>",
        Type::String | Type::Str => "::ketox::jni::sys::jstring",
        Type::Unit => "()",
    }
}

fn jni_default(ty: &Type) -> &'static str {
    match ty {
        Type::String | Type::Str => "::std::ptr::null_mut()",
        Type::F32 | Type::F64 => "0.0",
        Type::Unit => "()",
        _ => "0",
    }
}

// JNI symbol escaping operates on UTF-16 code units, including surrogate pairs.
fn jni_escape(value: &str) -> String {
    let mut output = String::new();
    for unit in value.encode_utf16() {
        match unit {
            0x30..=0x39 | 0x41..=0x5a | 0x61..=0x7a => {
                output.push(char::from_u32(u32::from(unit)).unwrap());
            }
            0x2f => output.push('_'),
            0x5f => output.push_str("_1"),
            0x3b => output.push_str("_2"),
            0x5b => output.push_str("_3"),
            _ => write!(output, "_0{unit:04x}").unwrap(),
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn module(source: &str) -> Module {
        parse_source(source, "dev.ketox.example", "RustApi", "ketox_example").unwrap()
    }

    #[test]
    fn jni_escaping_preserves_package_separators_and_escapes_underscores() {
        assert_eq!(
            jni_escape("dev/ketox_api/Rust_Api"),
            "dev_ketox_1api_Rust_1Api"
        );
        assert_eq!(jni_escape("[Ljava/lang/String;"), "_3Ljava_lang_String_2");
        assert_eq!(jni_escape("é😀"), "_000e9_0d83d_0de00");
    }

    #[test]
    fn generates_every_phase_one_type_and_valid_rust_syntax() {
        let module = module(
            r#"
            #[kotlin_export] pub fn invert(value: bool) -> bool { !value }
            #[kotlin_export] pub fn tiny(value: i8) -> i8 { value }
            #[kotlin_export] pub fn small(value: i16) -> i16 { value }
            #[kotlin_export] pub fn add(a: i32, b: i32) -> i32 { a + b }
            #[kotlin_export] pub fn big(value: i64) -> i64 { value }
            #[kotlin_export] pub fn single(value: f32) -> f32 { value }
            #[kotlin_export] pub fn double(value: f64) -> f64 { value }
            #[kotlin_export] pub fn hello(name: String) -> String { name }
            #[kotlin_export] pub fn text_length(value: &str) -> i32 { 0 }
            #[kotlin_export] pub fn ping() {}
            "#,
        );
        let generated = generate(&module).unwrap();
        syn::parse_file(&generated.rust).expect("generated JNI glue should be valid Rust");
        for declaration in [
            "external fun invert(value: kotlin.Boolean): kotlin.Boolean",
            "external fun tiny(value: kotlin.Byte): kotlin.Byte",
            "external fun small(value: kotlin.Short): kotlin.Short",
            "external fun add(a: kotlin.Int, b: kotlin.Int): kotlin.Int",
            "external fun big(value: kotlin.Long): kotlin.Long",
            "external fun single(value: kotlin.Float): kotlin.Float",
            "external fun double(value: kotlin.Double): kotlin.Double",
            "external fun hello(name: kotlin.String): kotlin.String",
            "external fun textLength(value: kotlin.String): kotlin.Int",
            "external fun ping(): kotlin.Unit",
        ] {
            assert!(
                generated.kotlin.contains(declaration),
                "missing {declaration}"
            );
        }
        assert!(
            generated
                .rust
                .contains("Java_dev_ketox_example_RustApi_textLength")
        );
        assert!(
            generated
                .rust
                .contains("crate::text_length(__ketox_value_0.as_str())")
        );
        assert!(generated.rust.contains("crate::invert(__ketox_arg_0 != 0)"));
        assert!(
            generated
                .rust
                .contains("Ok(if __ketox_result { 1 } else { 0 })")
        );
        assert!(!generated.kotlin.contains("@JvmStatic"));
        assert_eq!(
            generated
                .rust
                .matches("::ketox::runtime::boundary(")
                .count(),
            10
        );
    }

    #[test]
    fn artifacts_are_deterministic_and_metadata_round_trips() {
        let module = module("#[kotlin_export] pub fn hello(name: String) -> String { name }");
        let first = generate(&module).unwrap();
        assert_eq!(first, generate(&module).unwrap());
        let restored: Module = serde_json::from_str(&first.metadata).unwrap();
        assert_eq!(generate(&restored).unwrap(), first);
    }

    #[test]
    fn loader_explains_library_search_and_preserves_original_cause() {
        let generated = generate(&module("#[kotlin_export] pub fn ping() {}")).unwrap();
        assert!(
            generated
                .kotlin
                .contains("System.loadLibrary(\"ketox_example\")")
        );
        assert!(
            generated
                .kotlin
                .contains("System.getProperty(\"java.library.path\")")
        );
        assert!(generated.kotlin.contains("it.initCause(error)"));
    }

    #[test]
    fn malformed_metadata_is_rejected_before_interpolating_code() {
        let mut module = module("#[kotlin_export] pub fn ping() {}");
        module.library_name = "bad\"library".to_owned();
        assert!(generate(&module).is_err());
        module.library_name = "safe".to_owned();
        module.class_name = "../outside".to_owned();
        assert!(generate(&module).is_err());
    }

    #[test]
    fn internal_jni_variables_do_not_conflict_with_exported_parameter_names() {
        let generated = generate(&module(
            "#[kotlin_export] pub fn echo(env: String, result: bool, __ketox_arg_0: i32) -> String { env }",
        ))
        .unwrap();
        assert!(
            generated
                .rust
                .contains("crate::echo(__ketox_value_0, __ketox_arg_1 != 0, __ketox_arg_2)")
        );
        syn::parse_file(&generated.rust).unwrap();
    }

    #[test]
    fn kotlin_types_and_loader_are_qualified_to_avoid_object_name_shadowing() {
        let mut module = module("#[kotlin_export] pub fn echo(value: String) -> String { value }");
        module.class_name = "String".to_owned();
        let generated = generate(&module).unwrap();
        assert!(generated.kotlin.contains("object String {"));
        assert!(
            generated
                .kotlin
                .contains("echo(value: kotlin.String): kotlin.String")
        );
        module.class_name = "System".to_owned();
        let generated = generate(&module).unwrap();
        assert!(generated.kotlin.contains("java.lang.System.loadLibrary("));
        assert!(
            generated
                .kotlin
                .contains("error: java.lang.UnsatisfiedLinkError")
        );
    }
}
